### ISSUE TITLE
关于 POP to RK4

### ISSUE THREAD

**Issue by zhou1yu2wei3** [MartinRGB/MTGuideline#2]
使用 Rebound-js 中的那段转换代码得出的结果，似乎无法相对应，你有同样的问题吗？

**Comment by MartinRGB** [comment]
@zhou1yu2wei3 在 Rebound [SpringConfig](http://facebook.github.io/rebound/javadocs/) 里面有两个接口，**fromOrigamiTensionAndFriction**,**fromBouncinessAndSpeed**，你可能需要查看 源码去对应。

**Comment by MartinRGB** [comment]
@zhou1yu2wei3 而且那个转化好像当时研究的是 FramerJS -> QuartzComposer(POP) 里面的 参数，而 Rebound 和 设计软件里面的参数比例系数还有点差别。也就是虽然 QuartzComposer -> ReboundJS 用的是一套动画引擎，但是里面做了处理，在那个 API Docs 里面写了，如果你用 Tension 和 Friction 似乎是 OK 的。
