### ISSUE TITLE
ae获取贝塞尔数值的问题

### ISSUE THREAD

**Issue by cirnoc** [MartinRGB/MTGuideline#3]
您好，在「1.1 曲线和弹性动画的定义与开发」一文中，又看到您插入的第一张截图 关于ae的贝塞尔曲线数值，想请教下这个数值是如何获取的？

**Comment by MartinRGB** [comment]
> 您好，在「1.1 曲线和弹性动画的定义与开发」一文中，又看到您插入的第一张截图 关于ae的贝塞尔曲线数值，想请教下这个数值是如何获取的？


有个脚本 getBezier.jsx，现在的 Flow 也可以
